### ISSUE TITLE
Author not showing in new template

### ISSUE THREAD

**Issue by AndreasMadsen** [distillpub/post--memorization-in-rnns#15]
![skaermbillede 2019-02-14 kl 14 37 32](https://user-images.githubusercontent.com/505333/52790143-180fd900-3066-11e9-9668-c58fe666d4be.png)

I think the author field is the gray line that placed to the right. But it is not showing correctly at all.

**Comment by ludwigschubert** [comment]
It was just inside the wrong tag—fixed via a7249d8.

**Comment by AndreasMadsen** [comment]
Thanks :)
