### ISSUE TITLE
Final text editing pass

### ISSUE THREAD

**Issue by ludwigschubert** [distillpub/post--memorization-in-rnns#17]
I noticed some grammatical weirdness that I will need a native speaker to help judge and potentially resolve. Partly addressed in 6a06087 together with tonal inconsistencies, but I'm not confident enough to say I got everything. 

Not-To-Do: let's ensure we keep @AndreasMadsen's voice alive. Aim to only change text when grammatical constructs are ambiguous or wrong. This may include rolling back some of my attempts in 6a06087.

**Comment by ludwigschubert** [comment]
@AndreasMadsen I will aim to grab Chris (or another native speaker) by Monday EOD pacific time.

**Comment by AndreasMadsen** [comment]
Feel free to change the gramma. I'm not a native speaker myself so I tend to miss those details.

**Comment by ludwigschubert** [comment]
Chris and me made some further tweaks in 8fe8a6e. For any remaining typos I expect we'll see issues created on this repository as readers see the article. ;-)

**Comment by AndreasMadsen** [comment]
Looks fine. Thanks.
