### ISSUE TITLE
Decide on repo name and slug for distill publication

### ISSUE THREAD

**Issue by ludwigschubert** [distillpub/post--memorization-in-rnns#18]
The title of this article is "Visualizing memorization in RNNs", so I had went with a standard `memorization-in-rnns` for the slug and repo name. I then saw that Andreas [used `connectivity-visualization` as the suggested slug](https://github.com/distillpub/post--memorization-in-rnns/blob/master/article/index.html#L646) in the article. 

@AndreasMadsen do you feel strongly about using `connectivity-visualization` for repo name and slug? We aim to be consistent with the final title of the article, but I'm also happy to go with your suggestion if you'd prefer it! :-)

**Comment by ludwigschubert** [comment]
To be clear, this only affects these two URLs:

- `https://github.com/distillpub/post--memorization-in-rnns`
- `https://distill.pub/2019/memorization-in-rnns`

And is a purely aesthetic choice afaik. ;-)

**Comment by AndreasMadsen** [comment]
I don't care. Feel free to change it as you wish.

**Comment by ludwigschubert** [comment]
Gotcha; staying with what we have right now. (d684147) :-)
