### ISSUE TITLE
Please change absolute paths to relative ones

### ISSUE THREAD

**Issue by ludwigschubert** [distillpub/post--memorization-in-rnns#19]
Andreas, currently your article expected data in an absolute path, e.g. `/data/connectivity_gru.json`. This doesn't work when we deploy your article in a subdirectory such as `https://distill.pub/2019/memorization-in-rnns/`. Please ensure all links in your article and Javascript are relative. You can inspect errors [here on the staging server](https://staging.distill.pub/2019/memorization-in-rnns/). :-)

**Comment by AndreasMadsen** [comment]
Should be fixed in https://github.com/distillpub/post--memorization-in-rnns/commit/2f531e367f3043a51f9d6d701ab97e97e0f818ac
