### ISSUE TITLE
Typos, grammar issues and suggestions

### ISSUE THREAD

**Issue by GuilhermeFreire** [distillpub/post--memorization-in-rnns#22]
First off, great article! I particularly enjoyed its visualizations and interactive bits. However, I'd like to point out that while reading it I found some typos, grammar issues and other suggestions I'd like to make.

#### 1
There seems to be a word missing on the last sentence of the second paragraph:

> As such, developing new recurrent units that are better at memorization continues to an active field of research.

There's a "**be**" missing at the end. Inserting it, the sentence would become:

> As such, developing new recurrent units that are better at memorization continues to **be** an active field of research.

#### 2
The diagram showing the inner workings of the LSTM cell contains only **sigmoid** activations. However, the activation on `h^t_{l-1}` when multiplied with the input gate should be **tanh**. The same applies to the activation on `c^t_l` right before being multiplied with the output gate.

<img width="545" alt="Screen Shot 2019-03-25 at 10 55 14 PM" src="https://user-images.githubusercontent.com/9718154/54965992-9ad36000-4f51-11e9-9523-781059bf7cb8.png">

There's also something weird going on with the fonts of the two middle sigma symbols, not sure what's happening.

Everything said regarding the LSTM image also applies to the Nested LSTM image. The GRU image also needs an update.

#### 3
The captions for the "**Forget Gates**" and "**Input Gates**" in the Nested LSTM diagram both start with:

>  "**controls** how much[...]"

They should start with: 

> "**control** how much[...]"

#### 4
In the first sentence of the second paragraph of _Connectivity in the Autocomplete Problem_, "**captures**" should be "**capture**":
> This visualization was inspired by Karpathy et al. [7] where they identify cells that **capture** a specific feature.

#### 5
Following item **4**, the next sentence is:
> For identifying a specific feature, this visualization approach works well.

Which, in my opinion, would be better by changing its beginning:

> **To identify** a specific feature, this visualization approach works well.

#### 6
In the final graph, there's a typo in the label on the X axis:
> "**charecters** from word"

Should be:

> "**characters** from word"

#### 7
In the last paragraph before the conclusion, you wrote:
> While more detailed **qualitative** metrics like this provides new insight, qualitative analysis like the connectivity figure presented in this article still has great value.

Did you mean to write "**quantitative**" instead of "**qualitative**"? The sentence would become:

> While more detailed **quantitative** metrics like this provides new insight, qualitative analysis like the connectivity figure presented in this article still has great value.

**Comment by arjunchandra** [comment]
One more:
- The typical problems that are often used, such as Penn Treebank [4], Chinese Poetry Generation, or *text8* [5] generation

**Comment by AndreasMadsen** [comment]
Thanks, should be fixed in 61885268374d96abe1697e2f37d5e6578a9258aa. Hopefully it will be reuploaded soon.

**Comment by GuilhermeFreire** [comment]
@AndreasMadsen Checking 6188526, it seems like you changed "**controls**" to "**control**" on all RNN diagrams. What I meant to say on item **3** is that you should change it _only_ in the Nested LSTM image (since it has more than one of each gate). The vanilla LSTM and GRU should keep "**controls**" (since each only has one gate of each type).

**Comment by ludwigschubert** [comment]
@GuilhermeFreire reverted in 4a22c4b . @AndreasMadsen I'll redeploy your fixes now, thanks!

**Comment by ludwigschubert** [comment]
@AndreasMadsen uh, sorry, I realized I only undid the `aria-labels`, not the actual SVG—I'm afraid you'll have to handle that. 👀 The rule is that a singular subject ("update gate") needs an `s` after the verb: "the update gate control**s** xyz…", whereas plural subjects don't need that `s` after the verb: "the update gate**s** control_ xyz…".

**Comment by AndreasMadsen** [comment]
Thanks a lot for the help. I belive it should all be fixed in e25fb249682b23f62b48818c5a02cb62162fc3ef
