### ISSUE TITLE
Some writing improvement suggestions

### ISSUE THREAD

**Issue by Sparkier** [distillpub/post--memorization-in-rnns#23]
I really like the article, just noticed an error in your writing:
As such, developing new recurrent units that are better at memorization continues to **be** an active field of research.
The word be is missing here.

Also, a word is missing in the first paragraph of 'A problem for qualitative analysis'. 
Chinese Poetry Generation, or **text8** [5] generation do ...
I think there should be text8.

In paragraph two of 'Connectivity in the Autocomplete Problem':
cells that capture~~s~~
The singular s in captures should be removed.

**Comment by AndreasMadsen** [comment]
Thanks. All these have been fixed in master, I think @ludwigschubert just needs to republish it.
