### ISSUE TITLE
Wrong gate labels in GRU diagram

### ISSUE THREAD

**Issue by oscmansan** [distillpub/post--memorization-in-rnns#24]
I believe the labels for the update and reset gates in the GRU diagram are swapped. They point to the wrong gate, though the definition is correct.

**Comment by AndreasMadsen** [comment]
Wow. That is pretty embarrassing. Thanks! It is fixed in 2d3ca6cecaef3f5e2509e67e52c8a240d18aae2a

**Comment by oscmansan** [comment]
No problem, glad to help! I really enjoyed the article regardless :)
